# Generated by Django 4.2.7 on 2024-01-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_staff',
            new_name='admin',
        ),
        migrations.AddField(
            model_name='profile',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
