# Generated by Django 4.2.7 on 2024-01-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0002_rename_is_active_profile_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='active',
            new_name='is_active',
        ),
    ]
