services:
  app:
    build: .
    container_name: django-app
    command: "python manage.py runserver 0.0.0.0:8000"
    environment:
      - REDIS_HOST=cb
      - REDIS_PORT=6379
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cb
  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: sonarDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  cb:
    restart: unless-stopped
    image: redis:alpine
    expose:
      - 6379

volumes:
  postgres-data:
  cache: