# Generated by Django 4.2.7 on 2023-12-08 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collisions_as_user', to='core.profile')),
                ('viewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collisions_as_viewed_user', to='core.profile')),
            ],
            options={
                'unique_together': {('user', 'viewed_user')},
            },
        ),
    ]
