# Generated by Django 4.2.7 on 2023-12-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_game_icon_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='collision',
            name='match',
            field=models.BooleanField(default=False),
        ),
    ]
